### PR TITLE
Add LA to master

### LINKED ISSUE #34: wvargas10 - Los Angeles, CA
## Los Angeles, CA

- [x] Create a branch
- [x]  Add File
- [x]  Create a commit
- [x]  Open PR
- [ ] Have a discussion about PR
- [ ] Manage PR

### PR DESCRIPTION
**Pull request by wvargas10**
Closes #34

### CODE REVIEW

**Comment by wvargas10** [comment]
@wvargas10 Did I do this right?

**Comment by wvargas10** [comment]
@githubteacher Did I do this right?

**Comment by NatashaE** [comment]
LA is great 👍

**Comment by dschz** [comment]
👍 You are ready to 🚢

**Pull request merged**
